#!/bin/bash -l
prefix="MoS2"
for d in 0{2..2}*/; do
  mkdir -p $d/${prefix}.save
  ln -sf ../../01-scf/${prefix}.save/data-file-schema.xml $d/${prefix}.save
  ln -sf ../../01-scf/${prefix}.save/charge-density.dat $d/${prefix}.save
done

ln -sf ../QE/02-wfn/WFN ../Chi/WFN
