#!/bin/bash -l
#SBATCH --partition=debug
#SBATCH --nodes=2
#SBATCH --time=00:10:00
#SBATCH --job-name=my_job
#SBATCH --license=SCRATCH
#SBATCH -C haswell
#SBATCH --ntasks-per-node=32

# These variables work on NERSC/Cori2:
QE_BIN_DIR="/global/homes/m/mwu/softwares/QE/QE6.4.1/QE6.4.1_trunk/bin"
PW="${QE_BIN_DIR}/pw.x"
PW_INPUT="QE.in"
PW_OUTPUT="QE.out"
PW2BGW="${QE_BIN_DIR}/pw2bgw.x"
PW2BGW_INPUT="pw2bgw.inp"
PW2BGW_OUTPUT="pw2bgw.out"

MPIRUN="srun"
POOLS="-nk 8"
export OMP_NUM_THREADS=1

cd ./02-wfn
$MPIRUN $PW < ./${PW_INPUT} &> ./${PW_OUTPUT}
$MPIRUN $PW2BGW < ./${PW2BGW_INPUT} &> ./${PW2BGW_OUTPUT}
cd ..
